workflows:
  build:
    name: Build
    instance_type: mac_pro
    max_build_duration: 60
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    cache:
      cache_paths:
        - buck-out/cache
    scripts:
      - name: Run Ant
        script: ant
      - name: Install Buck
        script: |-
          #!/usr/bin/env bash
          # fail if any commands fails
          set -e
          # debug log
          set -x
          
          rm -rf bin/buck
          curl https://jitpack.io/com/github/traveloka/buck/477c9b99be3dae1c48bc6c9c4bc9e114ad9f5f56/477c9b99be3dae1c48bc6c9c4bc9e114ad9f5f56-java11.pex --output bin/buck
          chmod u+x bin/buck
      - name: Buck Build
        script: NO_BUCKD=1 bin/buck build buck
