workflows:
  build:
    name: Build
    instance_type: mac_pro
    max_build_duration: 60
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    cache:
      cache_paths:
        - buck-out/cache
    scripts:
      - name: Run Ant
        script: ant
      - name: Install Buck
        script: |
          #!/usr/bin/env bash
          # fail if any commands fails
          set -e
          # debug log
          set -x
          
          rm -rf bin/buck
          curl https://jitpack.io/com/github/facebook/buck/577c273d9746e42769e5dbb7bb5a092ba3ec82c2/buck-577c273d9746e42769e5dbb7bb5a092ba3ec82c2-java11.pex --output bin/buck
          chmod u+x bin/buck
      - name: Buck Build
        script: NO_BUCKD=1 bin/buck build buck
